config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'pages#home'

  authenticate :user do
    get '/feed', to: 'pages#feed'
  
    # profiles
    get 'profiles/me', to: 'profiles#index'
    get 'profiles/:id', to: 'profiles#show'
    post 'profiles/:id', to: 'profiles#send_follow_request'
    patch 'profiles/me', to: "profiles#update", as: "profile_update"
    # resources
    resources :tweets, except: [:new, :index]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  # validates
  validates :content, presence: true, length: {maximum: 280} 

  # mounts
  mount_uploaders :images, TweetImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  # validates
  validates :fullname, presence: true, length: {minimum: 3, maximum: 30}
  validates :username, presence: true, uniqueness: {case_sensitive: false}
  validates :location, length: {maximum: 20}
  # validates :website, format: {with: /(https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|www\.[a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]\.[^\s]{2,}|https?:\/\/(?:www\.|(?!www))[a-zA-Z0-9]+\.[^\s]{2,}|www\.[a-zA-Z0-9]+\.[^\s]{2,})/, message: "Please check your URL" }
  validates :bio, length: {maximum:160}

  # mounts
  mount_uploader :profile_picture, ProfilePictureUploader
  mount_uploader :profile_background_picture, ProfileBackgroundUploader

  # associations
  has_friendship
  has_many :tweets, dependent: :destroy
  
  # callbacks
  def on_friendship_created(friendship)
  end
  
  def on_friendship_accepted(friendship)
  end
  
  def on_friendship_blocked(friendship)
  end
  
  def on_friendship_destroyed(friendship)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception, prepend: true

  before_action :configure_permitted_parameters, if: :devise_controller?

  def check_signed_in
    redirect_to feed_path if signed_in?
  end

  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:fullname, :profile_picture, :bio, :username])
    end

    def after_sign_in_path_for(resource)
      feed_path
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:feed]
  before_action :check_signed_in, only: [:home]

  def home
  end

  def feed
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show, :send_follow_request]

  def index
  end

  def show
    if current_user == @user
      redirect_to profiles_me_path
    end
  end

  def update
    if current_user.update(profile_params)
      flash[:notice] = "Profile updated was successfully."
    else
      flash[:alert] = "Something went wrong."
    end
    redirect_to profiles_me_path
  end

  def send_follow_request
    current_user.friend_request(@user)
    @user.accept_request(current_user)
    render :json => {status: true}
  end

  private
    def set_user
      @user = User.find(params[:id])
    end

    def profile_params
      params.require(:user).permit(:fullname, :bio, :location, :website)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    if @tweet.save
      flash[:notice] = "Shared with successfully."
      redirect_to profiles_me_path
    else
      flash[:alert] = "Something went wrong."
      redirect_to profiles_me_path
    end
  end

  private
    def tweet_params
      params.require(:tweet).permit(:content, {:images => []})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def resource_class
    User
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/layouts/application.slim
doctype html
html
  head
    title Twitter Clone
    meta[name="viewport" content="width=device-width,initial-scale=1"]
    = favicon_link_tag 'favicon.ico'
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield
    = yield(:js)
    = render "devise/shared/alerts"

app/views/pages/feed.slim
.container
  .row.pt-3#main
    = render "shared/left_bar"
    .col-md-6.col-sm-12#main-feed
      .d-flex.justify-content-between
        h4 Home
        = icon('fas', 'magic')
      hr
      .row.hide-in-mobile(style="--bs-gutter-x: 0rem;padding: 10px 10px 10px 10px;")
        .col-md-2
          - if current_user.profile_picture?
            = image_tag current_user.profile_picture_url(:small), class: "hide-in-mobile"
          - else
            = image_tag  "default_profile.png", :style => "width: 45px; height: 45px;" , :class => "hide-in-mobile"
        .col-md-10
          textarea#tw-modal-txarea(rows="8" placeholder="What's happening?" maxlength="280")
        .col-md-12.d-flex#tw-modal-footer
          div
            = icon('fas', 'image')
          div
            = icon('fas', 'film')
          div
            = icon('fas', 'chart-bar')
          div
            = icon('fas', 'smile')
          div
            = icon('fas', 'calendar-alt')
          div
            button.btn.tw-btn.twitter-dark(style="height: calc(2.5rem + 2px);") Tweet
        hr.mt-2  
      - (0..20).each do |p|
        .tweet
          .row
            .col-md-1
              = image_tag  "default_profile.png", :style => "width: 45px; height: 45px;"
            .col-md-11
              .d-flex
                h6.fw-bold user#{p}&#160;
                h6.username @username#{p}&#160;|
                h6.username &#160;#{time_ago_in_words(DateTime.current.to_date)} ago
              p Lorem ipsum dolor, sit amet consectetur adipisicing elit. Eius, molestiae modi perspiciatis voluptatem eaque itaque odit illum hic sapiente veritatis. Dicta sequi eum eaque similique amet vel minus voluptate deleniti.
              - if p % 3 == 0
                = image_tag  "logo-dark.png", :class => "img-fluid tweet-image mb-2" 
            .col-md-12
              .d-flex.tweet-actions
                = icon('far', 'comment', class: 'comment')
                = icon('fas', 'retweet', class: 'retweet')
                = icon('far', 'heart', class: 'like')
                = icon('fas', 'share-square', class: 'share')
    = render "shared/right_bar"
= render "shared/tweet_modal"
//= link_to "Logout", destroy_user_session_path, class: "mt-5 ms-5", data: {:confirm => 'Are you sure?'}, method: :delete
//= current_user.as_json

app/views/pages/home.slim
.row#home-area
  .col-md-6#home-background.hide-in-mobile
  .col-md-6
    .container.pt-3
      = form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
        .row.hide-in-mobile
          .col-md-4
            .form-floating.mb-3
              = f.email_field :email, class: "form-control", placeholder: "Email"
              label Email
          .col-md-4
            .form-floating.mb-3
              = f.password_field :password, class: "form-control", placeholder: "Password"
              label Password  
          .col-md-4
            = f.submit "Log in", class: "btn tw-btn twitter-light fluid-in-mobile" do
              span Log in
      div
        .d-block
          = image_tag "logo-dark.png", style: 'height: 45px; width:auto;', :class => "mb-5 mt-5"
          h1.fw-bolder.mt-2(style="font-size: 64px;") Happening now
          h2.fw-bolder.mt-4 Join Twitter today.
          .d-grid.mt-5
            button.btn.tw-btn.twitter-dark.mb-4.fluid-in-mobile.w-50(type='button' data-bs-toggle='modal' data-bs-target='#signupModal') Sign up
            = link_to  "Log in", new_user_session_path, class: "btn tw-btn twitter-light fluid-in-mobile w-50"
css:
  html,body{
    width: 100vw;
    height: 100vh;
  }
= render "shared/signup_modal"

app/views/profiles/_profile.slim
.col-md-6.col-sm-12#main-feed
  .d-flex.justify-content-between
    h4 #{user.fullname}
  hr.mb-0
  - if user.profile_background_picture?
    = image_tag user.profile_background_picture_url(:cover), class: "img-fluid", alt: user.fullname
  - else
    = image_tag  "default_profile_background.png", :class => "img-fluid", alt: user.fullname
  div.profile-picture
    div
      - if user.profile_picture?
        = image_tag user.profile_picture.url(:medium) 
      - else
        = image_tag "default_profile.png", :style => "height: 135px; width:auto;"
  .pe-2.pt-2
    - if current_user == user
      button.btn.tw-btn.twitter-light.profile-edit(data-bs-toggle="modal" data-bs-target="#editProfileModal") Edit profile
    - else
      button.btn.tw-btn.twitter-light.profile-edit.follow-button Follow
  .profile-details
    h3 #{user.fullname}
    h6.username @#{user.username}
    - if user.bio?
      p #{user.bio}
    .profile-icons.d-flex
      - if user.location?
        = icon('fas', 'map-marker-alt') do
        small #{user.location}
      - if user.website?
        = icon('fas', 'link', class: 'ps-2')
        small.website #{user.website}
    .profile-icons
      - if user.birth_date?
        = icon('fas', 'birthday-cake')
        small #{user.birth_date.to_formatted_s(:short)}
      = icon('fas', 'calendar-alt', class: 'ps-2')
      small Joined #{user.created_at.to_formatted_s(:short)}
  .profile-tabs.mt-3
    ul.nav.justify-content-between
      li.nav-item.active Tweets
      li.nav-item Tweets & replies
      li.nav-item Media
      li.nav-item Likes
  .tweets
    - user.tweets.reverse_each do |tweet|
      = render "shared/tweet", tweet: tweet
#editProfileModal.modal.fade(tabindex='-1' aria-labelledby='editProfileModalLabel' aria-hidden='true')
  .modal-dialog.modal-dialog-centered
    = form_for(current_user, url: profile_update_path, html: {class: "modal-content"}) do |f|
      .modal-header
        h5#editProfileModalLabel.modal-title Edit profile
        button.btn-close(type='button' data-bs-dismiss='modal' aria-label='Close')
      .modal-body
        - if current_user.profile_background_picture?
          = image_tag current_user.profile_background_picture_url(:cover), class: "img-fluid", alt: current_user.fullname
        - else
          = image_tag  "default_profile_background.png", :class => "img-fluid", alt: current_user.fullname
        div.profile-picture
          div
            img.(src="https://pbs.twimg.com/profile_images/1228807164531281928/aiwKGIp__400x400.jpg" height="135")
        .form-floating.mb-3.mt-5r
          = f.text_field :fullname, placeholder: "Name", class: "form-control"
          label Name
        .form-floating.mb-3
          = f.text_area :bio, placeholder: "Bio", class: "form-control", style: "height: 150px"
          label Bio
        .form-floating.mb-3
          = f.text_field :location, placeholder: "Location", class: "form-control"
          label Location
        .form-floating.mb-3
          = f.url_field :website, placeholder: "Website", class: "form-control"
          label Website
      .modal-footer
        = f.submit "Save", class: "btn tw-btn twitter-dark", style: "height: calc(2.5rem + 2px);"
- content_for :js do
  javascript:
    $(document).on('turbolinks:load', function() {
      $("#edit-profile-btn")
    })
  

app/views/profiles/index.slim
.container
  .row.pt-3#main
    = render "shared/left_bar"
    = render "profiles/profile", user: current_user
    = render "shared/right_bar"
= render "shared/tweet_modal"
//= link_to "Logout", destroy_user_session_path, class: "mt-5 ms-5", data: {:confirm => 'Are you sure?'}, method: :delete
//= current_user.as_json

app/views/profiles/show.slim
.container
  .row.pt-3#main
    = render "shared/left_bar"
    = render "profiles/profile", user: @user
    = render "shared/right_bar"
= render "shared/tweet_modal"
javascript:
  $(document).on('turbolinks:load', function() {
    $(".follow-button").click(function() {
      $.ajax({
        type: "POST",
        url: window.location.href,
        success: function(res) {
          if (res.status == true) {
            toastr.success("Your friend request has been sent")
          } else {
            toastr.error("An error has occurred")
          }
        },
        error: function() {
          toastr.error("An error has occurred")
        }
      })
    })
  })
//= link_to "Logout", destroy_user_session_path, class: "mt-5 ms-5", data: {:confirm => 'Are you sure?'}, method: :delete
//= current_user.as_json

app/views/shared/_left_bar.slim
.col-md-3.hide-in-mobile
  = image_tag  "logo-dark.png", :style => "width: 40px; height: auto;", :class => "left-bar-logo"
  .d-block.mt-5#left-bar
    div
      = link_to feed_path, class: "tw-menu-item" do
        = icon('fas', 'home')
        |&nbsp;Home
    .mt-4
      = link_to feed_path, class: "tw-menu-item" do
        = icon('fas', 'hashtag')
        |&nbsp;Explore
    .mt-4
      = link_to feed_path, class: "tw-menu-item" do
        = icon('fas', 'bell')
        |&nbsp;Notification
    .mt-4
      = link_to feed_path, class: "tw-menu-item" do
        = icon('fas', 'envelope')
        |&nbsp;Messages
    .mt-4
      = link_to feed_path, class: "tw-menu-item" do
        = icon('fas', 'bookmark')
        |&nbsp;Bookmarks
    .mt-4
      = link_to feed_path, class: "tw-menu-item" do
        = icon('fas', 'list-alt')
        |&nbsp;Lists
    .mt-4
      = link_to profiles_me_path, class: "tw-menu-item" do
        = icon('fas', 'user')
        |&nbsp;Profile
    .mt-4
      = link_to feed_path, class: "tw-menu-item" do
        = icon('fas', 'ellipsis-h')
        |&nbsp;More
    .mt-4.d-grid.gap-2
      button.btn.tw-btn.twitter-dark.w-100(type="button" data-bs-toggle="modal" data-bs-target="#tweetModal") Tweet
  .d-flex.justify-content-between.user-footer
    .d-flex
      - if current_user.profile_picture?
        = image_tag current_user.profile_picture_url(:mini)
      - else
        = image_tag  "default_profile.png", :style => "width: 38px; height: 38px;"
      .d-block
        h6
          = current_user.fullname
        h6.username @#{current_user.username}
    = icon('fas', 'ellipsis-h')

app/views/shared/_right_bar.slim
.col-md-3.hide-in-mobile.ps-3
  #right-bar
    .input-group#search-area
      span.input-group-text
        = icon('fas', 'search')
      input.form-control#search-input(type='text' placeholder='Search Twitter')
    .right-bar-card.mt-5
      .d-flex.justify-content-between
        h4 Trends for you
        = icon('fas', 'cog')
      .right-bar-item
        .d-flex.justify-content-between
          div
            h6 test1
            .trend-count 45.000K
          = icon('fas', 'ellipsis-h')
      .right-bar-item
        .d-flex.justify-content-between
          div
            h6 test2
            .trend-count 45.000K
          = icon('fas', 'ellipsis-h')
      .right-bar-item
        .d-flex.justify-content-between
          div
            h6 test3
            .trend-count 45.000K
          = icon('fas', 'ellipsis-h')
      .right-bar-item
        .d-flex.justify-content-between
          div
            h6 test4
            .trend-count 45.000K
          = icon('fas', 'ellipsis-h')
      .right-bar-item
        .d-flex.justify-content-between
          div
            h6 test5
            .trend-count 45.000K
          = icon('fas', 'ellipsis-h')
      .right-bar-item
        .d-flex.last-right-bar-item.tw-text Show more
    .right-bar-card.mt-5
      .d-flex.justify-content-between
        h4 Who to follow
      .right-bar-item
        .d-flex.justify-content-between
          .d-flex
            = image_tag "default_profile.png", :style => "width: 45px; height: 45px;"
            .d-block.ps-2
              h6 user1
              .trend-count 45.000K
          button.btn.tw-btn.twitter-light.mini-follow-btn
            span Follow
      .right-bar-item
        .d-flex.justify-content-between
          .d-flex
            = image_tag "default_profile.png", :style => "width: 45px; height: 45px;"
            .d-block.ps-2
              h6 user2
              .trend-count 45.000K
          button.btn.tw-btn.twitter-light.mini-follow-btn
            span Follow
      .right-bar-item
        .d-flex.justify-content-between
          .d-flex
            = image_tag "default_profile.png", :style => "width: 45px; height: 45px;"
            .d-block.ps-2
              h6 user3
              .trend-count 45.000K
          button.btn.tw-btn.twitter-light.mini-follow-btn
            span Follow
      .right-bar-item
        .d-flex.last-right-bar-item.tw-text Show more

app/views/shared/_signup_modal.slim
#signupModal.modal.fade(tabindex='-1' aria-labelledby='signupModalLabel' aria-hidden='true')
  .modal-dialog.modal-dialog-centered.modal-lg
    .modal-content
      .modal-header
        h5#signupModalLabel.modal-title Create an account
        button.btn-close(type='button' data-bs-dismiss='modal' aria-label='Close')
      .modal-body.container(data-active-step="0")
        = form_for(resource, as: resource_name, url: registration_path(resource_name), local: false) do |f|
          .text-center
            = image_tag  "logo-dark.png", :class => "mt-5 mb-5", :style => "width: 45px; height: auto;"
          .step.d-block
            .form-floating.mb-3
              = f.text_field :fullname, class: "form-control", placeholder: "Fullname"
              label Fullname
            .form-floating
              = f.email_field :email, class: "form-control", placeholder: "Email"
              label(for='floatingPassword') Email
          .step.d-block
            .form-floating.mb-3
              = f.password_field :password, class: "form-control", placeholder: "Password"
              label Password
            .form-floating.mb-3
              = f.password_field :password_confirmation, class: "form-control", placeholder: "Password Confirmation"
              label Password Confirmation
          .step.d-block
            = f.file_field :profile_picture, class: "d-none", id: "pp-input"
            .mb-3
              = image_tag  "default_profile.png", :class => "rounded mx-auto d-block", :style => "width: 170px; height: 170px;", :id => "pp-image"
              .text-center
                button.btn.btn-link.text-decoration-none.mt-2#pp-btn(type='button') Upload a profile picture
                br
                small.mt-2 You can skip this step
          .step.d-block
            .form-floating.mb-3
              = f.text_field :bio, class: "form-control", placeholder: "Bio"
              label Bio
            .text-center
              br
              small.mt-2 You can skip this step
          .step.d-block
            .form-floating.mb-3
              = f.text_field :username, class: "form-control", placeholder: "Username"
              label Username
      .modal-footer
        button.btn.twt-btn#previous-step(type='button') Previous
        button.btn.twt-btn#next-step(type='button') Next
- content_for :js do 
  javascript:
    $(document).on('turbolinks:load', function() {

      let activeStep = parseInt($(".modal-body").attr("data-active-step"))

      // events
      $("#next-step").click(function() {
        if (activeStep == ($(".step").length -1)) {
          createAccount()
        }

        if (activeStep < ($(".step").length -1)) {
          activeStep++
          updateStep()
        }
      })

      $("#previous-step").click(function() {
        if (activeStep > 0) {
          activeStep--
          updateStep()
        }
      })

      $("#pp-btn").click(function(e) {
        $("#pp-input").click()
      })

      $("#pp-input").change(function(e) {
        $("#pp-image").attr("src", URL.createObjectURL(e.target.files[0]))
      })

      $('.modal').on('hidden.bs.modal', resetForm)

      // funcs
      function resetForm() {
        $(".new_user").trigger("reset")
        $("#pp-image").attr("src", "/assets/default_profile.png")
        activeStep = 0
        updateStep()        
      }

      function updateStep() {
        $('.step').each(function(index) {
          if (index == activeStep) {
            $(this).addClass("d-block")
            $(this).removeClass("d-none")
          } else {
            $(this).addClass("d-none")
            $(this).removeClass("d-block")
          }
        })

        updateButtons()
      }

      function updateButtons() {
        if (activeStep == 0) {
          $("#previous-step").prop('disabled', true)
        } else {
          $("#previous-step").prop('disabled', false)
        }

        if (activeStep == ($(".step").length -1)) {
          $("#next-step").html("Create an account")
        } else {
          $("#next-step").html("Next")
        }
      }

      function createAccount() {
        $(".new_user").submit()

      }

      updateStep()
    })

app/views/shared/_tweet.slim
.tweet
  .row
    .col-md-1
      - if tweet.user.profile_picture?
        = image_tag tweet.user.profile_picture.url(:small) 
      - else
        = image_tag  "default_profile.png", :style => "width: 45px; height: 45px;"
    .col-md-11
      .d-flex
        h6.fw-bold #{tweet.user.fullname}&#160;
        h6.username @#{tweet.user.username}
        h6.username &#160;#{time_ago_in_words(tweet.created_at)} ago
      p #{tweet.content}
      - tweet.images.each do |image|
        = image_tag image.url(:cover), class: "img-fluid"
    .col-md-12
      .d-flex.tweet-actions
        = icon('far', 'comment', class: 'comment')
        = icon('fas', 'retweet', class: 'retweet')
        = icon('far', 'heart', class: 'like')
        = icon('fas', 'share-square', class: 'share')

app/views/shared/_tweet_modal.slim
#tweetModal.modal.fade(tabindex='-1' aria-labelledby='tweetModalLabel' aria-hidden='true')
  = form_for(Tweet.new, url: tweets_path, html: {class: "modal-dialog"}) do |f| 
    .modal-content
      .modal-header
        - if current_user.profile_picture?
          = image_tag current_user.profile_picture_url(:small), class: "hide-in-desktop show-in-mobile"
        - else
          = image_tag  "default_profile.png", :style => "width: 45px; height: 45px;", :class => "hide-in-desktop show-in-mobile"
        button.btn-close.bg-twt(type='button' data-bs-dismiss='modal' aria-label='Close')
      .modal-body
        .row
          .col-md-2
            - if current_user.profile_picture?
              = image_tag current_user.profile_picture_url(:small), class: "hide-in-mobile"
            - else
              = image_tag  "default_profile.png", :style => "width: 45px; height: 45px;" , :class => "hide-in-mobile"
          .col-md-10
            = f.text_area :content, id: "tw-modal-txarea", rows: "8", placeholder: "What's happening?", maxlength: "280"
            = f.file_field :images, multiple: true, class: "d-none tw-modal-image-input"
      .modal-footer#tw-modal-footer
        div
          = icon('fas', 'image', class: "tw-modal-image-icon")
        div
          = icon('fas', 'film')
        div
          = icon('fas', 'chart-bar')
        div
          = icon('fas', 'smile')
        div
          = icon('fas', 'calendar-alt')
        div
          = f.submit "Tweet", class: "btn tw-btn twitter-dark", style: "height: calc(2.5rem + 2px);"            
- content_for :js do 
  javascript:
    $(document).on('turbolinks:load', function() {
      $(".tw-modal-image-icon").click(function() {
        $(".tw-modal-image-input").click()
      })
    })